### ISSUE TITLE
Hospitality mod apparently Pawn=/=Guest

### ISSUE THREAD

**Issue by feeddanoob** [kbatbouta/ISMA#1]
I know you are still sorting out the AI but latest commit https://github.com/kbatbouta/ISMA/commit/ba37600e6d0cb81c4d5002fa30af4d6de7498091 causes issues with hospitality. Here is the [HugsLib](https://gist.github.com/HugsLibRecordKeeper/34457239451c9e02c2a48c2a847ff16f)

**Comment by feeddanoob** [comment]
Don't hate me pls :X

**Comment by kbatbouta** [comment]
Thanks for the report. It's fixed now in the latest version.
